requirements

In [38]:
!pip install great-tables  #si non installé

Requirement already satisfied: great-tables in /opt/python/lib/python3.13/site-packages (0.21.0)
Requirement already satisfied: commonmark>=0.9.1 in /opt/python/lib/python3.13/site-packages (from great-tables) (0.9.1)
Requirement already satisfied: faicons>=0.2.2 in /opt/python/lib/python3.13/site-packages (from great-tables) (0.2.2)
Requirement already satisfied: htmltools>=0.4.1 in /opt/python/lib/python3.13/site-packages (from great-tables) (0.6.0)
Requirement already satisfied: importlib-metadata in /opt/python/lib/python3.13/site-packages (from great-tables) (8.7.1)
Requirement already satisfied: typing_extensions>=3.10.0.0 in /opt/python/lib/python3.13/site-packages (from great-tables) (4.15.0)
Requirement already satisfied: Babel>=2.13.1 in /opt/python/lib/python3.13/site-packages (from great-tables) (2.18.0)
Requirement already satisfied: importlib-resources in /opt/python/lib/python3.13/site-packages (from great-tables) (6.5.2)
Requirement already satisfied: packaging>=20.9 in /opt/python/lib/python3.13/site-packages (from htmltools>=0.4.1->great-tables) (26.0)
Requirement already satisfied: zipp>=3.20 in /opt/python/lib/python3.13/site-packages (from importlib-metadata->great-tables) (3.23.0)

In [39]:
import pandas as pd

In [40]:
import fonctions
import importlib
importlib.reload(fonctions)

Import des données

In [41]:
df = pd.read_csv(
 'https://www.data.gouv.fr/fr/datasets/r/182268fc-2103-4bcb-a850-6cf90b02a9eb'
)

/tmp/ipykernel_1770/3633677116.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

Import des fonctions du fichier fonctions.py nécessaires au DM

In [42]:
from fonctions import *

la tete des données ça ressemble à quoi

In [43]:
df.head(5)

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix
0,01,Ain,1,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3
1,01,Ain,2,L'Abergement-de-Varey,Nathalie,ARTHAUD,2
2,01,Ain,4,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38
3,01,Ain,5,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8
4,01,Ain,6,Ambléon,Nathalie,ARTHAUD,0

**Question 1**

In [44]:
#vérification du format : pour que "01" reste "01" et ne devienne pas "1"
df["code_departement"] = df["code_departement"].astype(str).str.zfill(2)
df["code_commune"] = df["code_commune"].astype(str).str.zfill(3)

df["code_commune"] = df["code_departement"] + df["code_commune"]

df["candidat"] = df["prenom"].fillna("") + " " + df["nom"].fillna("")

vérification de la manip

In [45]:
df.head(5)

,code_departement,libelle_departement,code_commune,libelle_commune,prenom,nom,voix,candidat
0,01,Ain,01001,L'Abergement-Clémenciat,Nathalie,ARTHAUD,3,Nathalie ARTHAUD
1,01,Ain,01002,L'Abergement-de-Varey,Nathalie,ARTHAUD,2,Nathalie ARTHAUD
2,01,Ain,01004,Ambérieu-en-Bugey,Nathalie,ARTHAUD,38,Nathalie ARTHAUD
3,01,Ain,01005,Ambérieux-en-Dombes,Nathalie,ARTHAUD,8,Nathalie ARTHAUD
4,01,Ain,01006,Ambléon,Nathalie,ARTHAUD,0,Nathalie ARTHAUD

vérifions si on a bien gardé les bulletins abstentions, blancs ou nuls

In [46]:
df["candidat"].str.contains("BLANC|NUL|ABSTENTION", case=False, na=False).any()

np.True_

Question 2

In [47]:
fonctions.compter_candidats(df)

"En 2022, il y avait 12 candidats à l'élection présidentielle."


Question 3

résultat en basique

In [48]:
fonctions.scores_nationaux_2(df)

                 Candidat  Nombre de votes (total) Score (% votes exprimés)
1         Emmanuel MACRON                  9783058                   27.85%
5           Marine LE PEN                  8133828                   23.15%
4      Jean-Luc MÉLENCHON                  7712520                   21.95%
11           Éric ZEMMOUR                  2485226                    7.07%
9        Valérie PÉCRESSE                  1679001                    4.78%
10          Yannick JADOT                  1627853                    4.63%
3           Jean LASSALLE                  1101387                    3.13%
2          Fabien ROUSSEL                   802422                    2.28%
7   Nicolas DUPONT-AIGNAN                   725176                    2.06%
0            Anne HIDALGO                   616478                    1.75%
8         Philippe POUTOU                   268904                    0.77%
6        Nathalie ARTHAUD                   197094                    0.56%

en joli tableau :

In [49]:
from great_tables import GT

GT(fonctions.scores_nationaux_2(df)).tab_header(
    title="Résultats Présidentielles 2022 (T1)"
)

GT(_tbl_data=                 Candidat  Nombre de votes (total) Score (% votes exprimés)
1         Emmanuel MACRON                  9783058                   27.85%
5           Marine LE PEN                  8133828                   23.15%
4      Jean-Luc MÉLENCHON                  7712520                   21.95%
11           Éric ZEMMOUR                  2485226                    7.07%
9        Valérie PÉCRESSE                  1679001                    4.78%
10          Yannick JADOT                  1627853                    4.63%
3           Jean LASSALLE                  1101387                    3.13%
2          Fabien ROUSSEL                   802422                    2.28%
7   Nicolas DUPONT-AIGNAN                   725176                    2.06%
0            Anne HIDALGO                   616478                    1.75%
8         Philippe POUTOU                   268904                    0.77%
6        Nathalie ARTHAUD                   197094                    0.56%, _body=<great_tables._gt_data.Body object at 0x7fe5e4e67230>, _boxhead=Boxhead([ColInfo(var='Candidat', type=<ColInfoTypeEnum.default: 1>, column_label='Candidat', column_align='left', column_width=None), ColInfo(var='Nombre de votes (total)', type=<ColInfoTypeEnum.default: 1>, column_label='Nombre de votes (total)', column_align='right', column_width=None), ColInfo(var='Score (% votes exprimés)', type=<ColInfoTypeEnum.default: 1>, column_label='Score (% votes exprimés)', column_align='right', column_width=None)]), _stub=<great_tables._gt_data.Stub object at 0x7fe5e5097c50>, _spanners=Spanners([]), _heading=Heading(title='Résultats Présidentielles 2022 (T1)', subtitle=None, preheader=None), _stubhead=None, _summary_rows=<great_tables._gt_data.SummaryRows object at 0x7fe5468f65d0>, _summary_rows_grand=<great_tables._gt_data.SummaryRows object at 0x7fe5e4e66fd0>, _source_notes=[], _footnotes=[], _styles=[], _locale=<great_tables._gt_data.Locale object at 0x7fe5468f6710>, _formats=[], _substitutions=[], _col_merge=[], _options=Options(table_id=OptionsInfo(scss=False, category='table', type='value', value=None), table_caption=OptionsInfo(scss=False, category='table', type='value', value=None), table_width=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_layout=OptionsInfo(scss=True, category='table', type='value', value='fixed'), table_margin_left=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_margin_right=OptionsInfo(scss=True, category='table', type='px', value='auto'), table_background_color=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_additional_css=OptionsInfo(scss=False, category='table', type='values', value=[]), table_font_names=OptionsInfo(scss=False, category='table', type='values', value=['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Helvetica Neue', 'Fira Sans', 'Droid Sans', 'Arial', 'sans-serif']), table_font_size=OptionsInfo(scss=True, category='table', type='px', value='16px'), table_font_weight=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_style=OptionsInfo(scss=True, category='table', type='value', value='normal'), table_font_color=OptionsInfo(scss=True, category='table', type='value', value='#333333'), table_font_color_light=OptionsInfo(scss=True, category='table', type='value', value='#FFFFFF'), table_border_top_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_top_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_top_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_top_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_right_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_right_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_right_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), table_border_bottom_include=OptionsInfo(scss=False, category='table', type='boolean', value=True), table_border_bottom_style=OptionsInfo(scss=True, category='table', type='value', value='solid'), table_border_bottom_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_bottom_color=OptionsInfo(scss=True, category='table', type='value', value='#A8A8A8'), table_border_left_style=OptionsInfo(scss=True, category='table', type='value', value='none'), table_border_left_width=OptionsInfo(scss=True, category='table', type='px', value='2px'), table_border_left_color=OptionsInfo(scss=True, category='table', type='value', value='#D3D3D3'), heading_background_color=OptionsInfo(scss=True, category='heading', type='value', value=None), heading_align=OptionsInfo(scss=True, category='heading', type='value', value='center'), heading_title_font_size=OptionsInfo(scss=True, category='heading', type='px', value='125%'), heading_title_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_subtitle_font_size=OptionsInfo(scss=True, category='heading', type='px', value='85%'), heading_subtitle_font_weight=OptionsInfo(scss=True, category='heading', type='value', value='initial'), heading_padding=OptionsInfo(scss=True, category='heading', type='px', value='4px'), heading_padding_horizontal=OptionsInfo(scss=True, category='heading', type='px', value='5px'), heading_border_bottom_style=OptionsInfo(scss=True, category='heading', type='value', value='solid'), heading_border_bottom_width=OptionsInfo(scss=True, category='heading', type='px', value='2px'), heading_border_bottom_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), heading_border_lr_style=OptionsInfo(scss=True, category='heading', type='value', value='none'), heading_border_lr_width=OptionsInfo(scss=True, category='heading', type='px', value='1px'), heading_border_lr_color=OptionsInfo(scss=True, category='heading', type='value', value='#D3D3D3'), column_labels_background_color=OptionsInfo(scss=True, category='column_labels', type='value', value=None), column_labels_font_size=OptionsInfo(scss=True, category='column_labels', type='px', value='100%'), column_labels_font_weight=OptionsInfo(scss=True, category='column_labels', type='value', value='normal'), column_labels_text_transform=OptionsInfo(scss=True, category='column_labels', type='value', value='inherit'), column_labels_padding=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_padding_horizontal=OptionsInfo(scss=True, category='column_labels', type='px', value='5px'), column_labels_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), column_labels_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), column_labels_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), column_labels_border_top_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_top_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_top_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_bottom_style=OptionsInfo(scss=True, category='column_labels', type='value', value='solid'), column_labels_border_bottom_width=OptionsInfo(scss=True, category='column_labels', type='px', value='2px'), column_labels_border_bottom_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_border_lr_style=OptionsInfo(scss=True, category='column_labels', type='value', value='none'), column_labels_border_lr_width=OptionsInfo(scss=True, category='column_labels', type='px', value='1px'), column_labels_border_lr_color=OptionsInfo(scss=True, category='column_labels', type='value', value='#D3D3D3'), column_labels_hidden=OptionsInfo(scss=False, category='column_labels', type='boolean', value=False), row_group_background_color=OptionsInfo(scss=True, category='row_group', type='value', value=None), row_group_font_size=OptionsInfo(scss=True, category='row_group', type='px', value='100%'), row_group_font_weight=OptionsInfo(scss=True, category='row_group', type='value', value='initial'), row_group_text_transform=OptionsInfo(scss=True, category='row_group', type='value', value='inherit'), row_group_padding=OptionsInfo(scss=True, category='row_group', type='px', value='8px'), row_group_padding_horizontal=OptionsInfo(scss=True, category='row_group', type='px', value='5px'), row_group_border_top_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_top_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_top_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_right_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_right_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_right_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_bottom_style=OptionsInfo(scss=True, category='row_group', type='value', value='solid'), row_group_border_bottom_width=OptionsInfo(scss=True, category='row_group', type='px', value='2px'), row_group_border_bottom_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_border_left_style=OptionsInfo(scss=True, category='row_group', type='value', value='none'), row_group_border_left_width=OptionsInfo(scss=True, category='row_group', type='px', value='1px'), row_group_border_left_color=OptionsInfo(scss=True, category='row_group', type='value', value='#D3D3D3'), row_group_as_column=OptionsInfo(scss=False, category='row_group', type='boolean', value=False), table_body_hlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_hlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_hlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_vlines_style=OptionsInfo(scss=True, category='table_body', type='value', value='none'), table_body_vlines_width=OptionsInfo(scss=True, category='table_body', type='px', value='1px'), table_body_vlines_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_top_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_top_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_top_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), table_body_border_bottom_style=OptionsInfo(scss=True, category='table_body', type='value', value='solid'), table_body_border_bottom_width=OptionsInfo(scss=True, category='table_body', type='px', value='2px'), table_body_border_bottom_color=OptionsInfo(scss=True, category='table_body', type='value', value='#D3D3D3'), data_row_padding=OptionsInfo(scss=True, category='data_row', type='px', value='8px'), data_row_padding_horizontal=OptionsInfo(scss=True, category='data_row', type='px', value='5px'), stub_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), stub_row_group_background_color=OptionsInfo(scss=True, category='stub', type='value', value=None), stub_row_group_font_size=OptionsInfo(scss=True, category='stub', type='px', value='100%'), stub_row_group_font_weight=OptionsInfo(scss=True, category='stub', type='value', value='initial'), stub_row_group_text_transform=OptionsInfo(scss=True, category='stub', type='value', value='inherit'), stub_row_group_border_style=OptionsInfo(scss=True, category='stub', type='value', value='solid'), stub_row_group_border_width=OptionsInfo(scss=True, category='stub', type='px', value='2px'), stub_row_group_border_color=OptionsInfo(scss=True, category='stub', type='value', value='#D3D3D3'), grand_summary_row_padding=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='8px'), grand_summary_row_padding_horizontal=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='5px'), grand_summary_row_background_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value=None), grand_summary_row_text_transform=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='inherit'), grand_summary_row_border_style=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='double'), grand_summary_row_border_width=OptionsInfo(scss=True, category='grand_summary_row', type='px', value='6px'), grand_summary_row_border_color=OptionsInfo(scss=True, category='grand_summary_row', type='value', value='#D3D3D3'), source_notes_padding=OptionsInfo(scss=True, category='source_notes', type='px', value='4px'), source_notes_padding_horizontal=OptionsInfo(scss=True, category='source_notes', type='px', value='5px'), source_notes_background_color=OptionsInfo(scss=True, category='source_notes', type='value', value=None), source_notes_font_size=OptionsInfo(scss=True, category='source_notes', type='px', value='90%'), source_notes_border_bottom_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_bottom_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_bottom_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_border_lr_style=OptionsInfo(scss=True, category='source_notes', type='value', value='none'), source_notes_border_lr_width=OptionsInfo(scss=True, category='source_notes', type='px', value='2px'), source_notes_border_lr_color=OptionsInfo(scss=True, category='source_notes', type='value', value='#D3D3D3'), source_notes_multiline=OptionsInfo(scss=False, category='source_notes', type='boolean', value=True), source_notes_sep=OptionsInfo(scss=False, category='source_notes', type='value', value=' '), row_striping_background_color=OptionsInfo(scss=True, category='row', type='value', value='#F4F4F4'), row_striping_include_stub=OptionsInfo(scss=False, category='row', type='boolean', value=False), row_striping_include_table_body=OptionsInfo(scss=False, category='row', type='boolean', value=False), container_width=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_height=OptionsInfo(scss=False, category='container', type='px', value='auto'), container_padding_x=OptionsInfo(scss=False, category='container', type='px', value='0px'), container_padding_y=OptionsInfo(scss=False, category='container', type='px', value='10px'), container_overflow_x=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), container_overflow_y=OptionsInfo(scss=False, category='container', type='overflow', value='auto'), quarto_disable_processing=OptionsInfo(scss=False, category='quarto', type='logical', value=False), quarto_use_bootstrap=OptionsInfo(scss=False, category='quarto', type='logical', value=False)), _google_font_imports=GoogleFontImports(imports=frozenset()), _has_built=False)

Question 4

In [50]:
fonctions.scores_departements(df)

     code_departement               candidat  votes   score
1                  01        Emmanuel MACRON  92206  27.69%
5                  01          Marine LE PEN  86755  26.05%
4                  01     Jean-Luc MÉLENCHON  57832  17.37%
11                 01           Éric ZEMMOUR  27530   8.27%
9                  01       Valérie PÉCRESSE  17572   5.28%
...               ...                    ...    ...     ...
1291      fr_etranger  Nicolas DUPONT-AIGNAN   7074   1.42%
1287      fr_etranger          Jean LASSALLE   5964    1.2%
1286      fr_etranger         Fabien ROUSSEL   3266   0.65%
1292      fr_etranger        Philippe POUTOU   3145   0.63%
1290      fr_etranger       Nathalie ARTHAUD   1300   0.26%

[1296 rows x 4 columns]

vérification avec le dep de l'Aude (11)

In [51]:
df_dep = fonctions.scores_departements(df)
df_11 = df_dep[df_dep["code_departement"] == "11"]
df_11

    code_departement               candidat  votes   score
125               11          Marine LE PEN  64027  30.14%
121               11        Emmanuel MACRON  43104  20.29%
124               11     Jean-Luc MÉLENCHON  42039  19.79%
131               11           Éric ZEMMOUR  18434   8.68%
123               11          Jean LASSALLE  12382   5.83%
129               11       Valérie PÉCRESSE   7350   3.46%
130               11          Yannick JADOT   6322   2.98%
120               11           Anne HIDALGO   6166    2.9%
122               11         Fabien ROUSSEL   5622   2.65%
127               11  Nicolas DUPONT-AIGNAN   4206   1.98%
128               11        Philippe POUTOU   1748   0.82%
126               11       Nathalie ARTHAUD   1026   0.48%

Question 5

In [52]:
import fonctions
import importlib
importlib.reload(fonctions)

df_11 = fonctions.comparaison_departement(df, 11)

fonctions.comparaison_departement(df, 11)

KeyError: 'candidat'

à executer si ça marche pas

In [ ]:
dir(fonctions)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'compter_candidats',
 'pd',
 'scores_departements',
 'scores_nationaux_2']